import { Pokemon } from "./pokemon";
import { Pokebola } from "./pokebola";
import { GreatBall } from "./GreatBall";
import { HealBall } from "./HealBall";
import { HeavyBall } from "./HeavyBall";

const pokemons = {
    todos : ["Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch’d",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew"],
    random() {
        return this.todos[Math.floor(Math.random() * this.todos.length)];
    }
}

function imprimirPokemon({nome, nivel, sexo, peso, pvMax, pvAtual}: Pokemon): void {
    console.log(`${nome}[${sexo}] no nivel ${nivel} com pv ${pvAtual}/${pvMax} pesando ${peso} kg`);
}

const pokebolas = [new Pokebola(), new GreatBall(), new HealBall(),
     new HealBall(), new HeavyBall(), new HeavyBall(), new HeavyBall() ];

let pokemon = new Pokemon(pokemons.random(), 2.2, 1.5, 100);

while (pokebolas.length > 0) {    
    const pokebola = pokebolas.pop();
    console.log(`Usando uma ${pokebola?.nome}`);
    imprimirPokemon(pokemon);
    if(pokebola?.capturar(pokemon)){        
        imprimirPokemon(pokemon);
        console.log("Capturado!!!");
        console.log("----");
        pokemon = new Pokemon(pokemons.random(), 2.2, 1.5, 100);
    }

}



